name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run specs
    strategy:
      matrix:
        ruby-version: ['2.7']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run rspec
        run: |
          cd spec/dummy
          bundle
          bundle exec rails db:test:prepare
          cd ../..
          bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    name: Run rubocop
    strategy:
      matrix:
        ruby-version: ['2.7']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run rubocop
        run: |
          bundle exec rubocop
